[project]
name = "lootbox"
authors = []
description = ""
telemetry = false
requirements = []
boot_contracts = ["pox", "costs-v2", "bns"]

[project.cache_location]
path = ".requirements"

[contracts.background-item]
path = "contracts/background-item.clar"

[contracts.lootbox-background]
path = "contracts/lootbox-background.clar"

[contracts.nft-trait]
path = "contracts/nft-trait.clar"

[contracts.send-lootbox]
path = "contracts/send-lootbox.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
